site_name: HC的博客
theme:
  name: material
  language: zh
  logo: logo.jpg
  favicon: logo.jpg
  features:
  - header.autohide
  - navigation.footer
  icon:
    repo: fontawesome/brands/github
  palette: 

  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - glightbox
  - blog:
      blog_dir: .
      blog_toc: true

markdown_extensions:
  - toc:
      permalink: true

repo_url: https://github.com/how-dare-you/hc_blog
repo_name: how-dare-you/hc_blog