site_name: HC的博客
theme:
  name: material
  language: zh
  logo: logo.jpg
  favicon: logo.jpg
  custom_dir: overrides
  features:
  - header.autohide
  # - navigation.footer
  - content.code.copy
  - content.code.annotate

  icon:
    repo: fontawesome/brands/github
  palette: 

  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - glightbox
  - blog:
      blog_dir: .
      blog_toc: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
repo_url: https://github.com/how-dare-you/hc_blog
repo_name: how-dare-you/hc_blog